### ISSUE TITLE
flowthings.drop(<flow-id>).aggregate({<params>}) undefined

### ISSUE THREAD

**Issue by AleksandarS** [flowthings/angular-client#2]
Hello,
I'm using your Flowthings angular client, and it works great but only Aggregation is not working, I mean, I cant set it up to work. 

The error I'm getting is 

```
Error: flowthings.drop("<flow-id>").aggregate is not a function. (In 'flowthings.drop("<flow-id>").aggregate', 'flowthings.drop("<flow-id>").aggregate' is undefined
```

And how I'm calling it is:

```
flowthings.drop("<flow-id>").aggregate({
        filter: "",
        groupBy:["$day"],
        output:["$avg:someworkingvalue"],
        rules: {}
    }).......
```

So I want to ask am I doing it right or is it some other issue?
As this aggregation I do through Postman (with this params) and it works.
Also everything else is same as other parts of the code which are working ( websockets and drop read and etc.)

Thank you for your time,
Alex

**Comment by natefaubion** [comment]
Are you using the correct versions of both flowthings-browser and flowthings-angular? flowthings-angular is just a thin adapter around flowthings-browser, so they require compatible versions. For example, if you updated flowthings-angular without also updating flowthings-browser, you might get this error as `aggregate` was just added. I have a [test for the aggregate function](https://github.com/flowthings/angular-client/blob/6f6f777b498f369c8b324032628e6f50117d5980/test/test.js#L183-L202), so this error should not be happening with a compatible library.

**Comment by AleksandarS** [comment]
True :) 

Thank you for ultra fast answer, it happened as I used one of them from another flowthings angular project, but now I updated both flowthings-browser and flowthings-angular and it works amazing.

Thank you for your time,
Alex
